// <auto-generated />
using System;
using Farmacia.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farmacia.WebApi.Migrations
{
    [DbContext(typeof(DbDataAccess))]
    [Migration("20260619000000_AgregarProveedorClienteSucursal")]
    partial class AgregarProveedorClienteSucursal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Farmacia.Entities.Cliente", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Nombre").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Apellido").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Dni").HasMaxLength(15).HasColumnType("nvarchar(15)");
                    b.Property<string>("Email").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Farmacia.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("RazonSocial").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Telefono").HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Email").HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.HasKey("Id");
                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Farmacia.Entities.Sucursal", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Nombre").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Direccion").HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Telefono").HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.HasKey("Id");
                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Farmacia.Entities.ProveedorMedicamento", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("IdProveedor").HasColumnType("int");
                    b.Property<int>("IdMedicamento").HasColumnType("int");
                    b.Property<decimal>("PrecioProveedor").HasColumnType("decimal(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("IdProveedor");
                    b.HasIndex("IdMedicamento");
                    b.ToTable("ProveedorMedicamentos");
                });

            modelBuilder.Entity("Farmacia.Entities.Venta", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("Fecha").HasColumnType("datetime2");
                    b.Property<int>("IdCliente").HasColumnType("int");
                    b.Property<int>("IdSucursal").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("IdCliente");
                    b.HasIndex("IdSucursal");
                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Farmacia.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("IdVenta").HasColumnType("int");
                    b.Property<int>("IdMedicamento").HasColumnType("int");
                    b.Property<int>("Cantidad").HasColumnType("int");
                    b.Property<decimal>("PrecioUnitario").HasColumnType("decimal(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("IdVenta");
                    b.HasIndex("IdMedicamento");
                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("Farmacia.Entities.ProveedorMedicamento", b =>
                {
                    b.HasOne("Farmacia.Entities.Proveedor", "Proveedor")
                        .WithMany("ProveedorMedicamentos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Farmacia.Entities.Medicamento", "Medicamento")
                        .WithMany("ProveedorMedicamentos")
                        .HasForeignKey("IdMedicamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Proveedor");
                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Farmacia.Entities.Venta", b =>
                {
                    b.HasOne("Farmacia.Entities.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Farmacia.Entities.Sucursal", "Sucursal")
                        .WithMany("Ventas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Cliente");
                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Farmacia.Entities.DetalleVenta", b =>
                {
                    b.HasOne("Farmacia.Entities.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Farmacia.Entities.Medicamento", "Medicamento")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdMedicamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Venta");
                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Farmacia.Entities.Cliente", b => { b.Navigation("Ventas"); });
            modelBuilder.Entity("Farmacia.Entities.Sucursal", b => { b.Navigation("Ventas"); });
            modelBuilder.Entity("Farmacia.Entities.Proveedor", b => { b.Navigation("ProveedorMedicamentos"); });
            modelBuilder.Entity("Farmacia.Entities.Medicamento", b =>
                {
                    b.Navigation("ProveedorMedicamentos");
                    b.Navigation("DetallesVenta");
                });
            modelBuilder.Entity("Farmacia.Entities.Venta", b => { b.Navigation("DetallesVenta"); });
#pragma warning restore 612, 618
        }
    }
}
